chapter: 10
name: Permit All Contracts
objects:
  - {class: vzFilter, dn: uni/tn-TN_POC/flt-FLT_WEB_APP_PERMIT_ALL, attributes: {name: FLT_WEB_APP_PERMIT_ALL, descr: Cisco ACI LAB Guide}}
  - {class: vzEntry, dn: uni/tn-TN_POC/flt-FLT_WEB_APP_PERMIT_ALL/e-PERMIT_ALL, attributes: {name: PERMIT_ALL, etherT: unspecified}}
  - {class: vzBrCP, dn: uni/tn-TN_POC/brc-web_app, attributes: {name: web_app, scope: tenant, descr: Cisco ACI LAB Guide}}
  - {class: vzSubj, dn: uni/tn-TN_POC/brc-web_app/subj-SUBJ_WEB_APP, attributes: {name: SUBJ_WEB_APP}}
  - {class: vzRsSubjFiltAtt, dn: "uni/tn-TN_POC/brc-web_app/subj-SUBJ_WEB_APP/rssubjFiltAtt-FLT_WEB_APP_PERMIT_ALL", attributes: {tnVzFilterName: FLT_WEB_APP_PERMIT_ALL}}
  - {class: fvRsCons, dn: uni/tn-TN_POC/ap-AP_POC/epg-EPG_WEB/rscons-web_app, attributes: {tnVzBrCPName: web_app}}
  - {class: fvRsProv, dn: uni/tn-TN_POC/ap-AP_POC/epg-EPG_AP/rsprov-web_app, attributes: {tnVzBrCPName: web_app}}
  - {class: vzFilter, dn: uni/tn-TN_POC/flt-FLT_APP_DB_PERMIT_ALL, attributes: {name: FLT_APP_DB_PERMIT_ALL, descr: Cisco ACI LAB Guide}}
  - {class: vzEntry, dn: uni/tn-TN_POC/flt-FLT_APP_DB_PERMIT_ALL/e-PERMIT_ALL, attributes: {name: PERMIT_ALL, etherT: unspecified}}
  - {class: vzBrCP, dn: uni/tn-TN_POC/brc-app_db, attributes: {name: app_db, scope: tenant, descr: Cisco ACI LAB Guide}}
  - {class: vzSubj, dn: uni/tn-TN_POC/brc-app_db/subj-SUBJ_APP_DB, attributes: {name: SUBJ_APP_DB}}
  - {class: vzRsSubjFiltAtt, dn: "uni/tn-TN_POC/brc-app_db/subj-SUBJ_APP_DB/rssubjFiltAtt-FLT_APP_DB_PERMIT_ALL", attributes: {tnVzFilterName: FLT_APP_DB_PERMIT_ALL}}
  - {class: fvRsCons, dn: uni/tn-TN_POC/ap-AP_POC/epg-EPG_AP/rscons-app_db, attributes: {tnVzBrCPName: app_db}}
  - {class: fvRsProv, dn: uni/tn-TN_POC/ap-AP_POC/epg-EPG_DB/rsprov-app_db, attributes: {tnVzBrCPName: app_db}}

